server:
  port: 8087
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: api-boss
  redis:
    host: 192.168.111.128
    port: 6379
    database: 0
